### ISSUE TITLE
NAT-Gateway cannot be created

### ISSUE THREAD

**Issue by bshyrokov** [g42cloud-terraform/terraform-provider-g42cloud#18]
Terraform v0.13.4

    provider registry.terraform.io/g42cloud-terraform/g42cloud v0.3.0
    provider registry.terraform.io/hashicorp/random v3.1.0
    provider[registry.terraform.io/huaweicloud/huaweicloud] 1.23.0
    
### Affected Resource(s)
- huaweicloud_nat_gateway

- g42cloud_nat_gateway is missing in the provider

### Terraform Configuration Files

https://gist.github.com/bshyrokov/1695e5972ab8643305ce5fdde2e5a5aa

### Debug Output

https://gist.github.com/bshyrokov/39818c76d6a037437e0d38857d3fcd86

### Expected Behavior

Create the NAT Gateway

Actual Behavior
```
Error: Error creatting Nat Gateway: Resource not found: [POST https://nat.ae-ad-1.vb.g42cloud.com:443/v2/82c38c977e8d43cab7af450f4b276257/nat_gateways], error message: {"error_msg":"The API does not exist or has not been published in the environment","error_code":"APIGW.0101","request_id":"e8a7d48464acd752f3b77db5a78c3f21"}
```

Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`

Important Factoids

The user which runs terraform can create NAT Gateway in the web console.

**Comment by niuzhenguo** [comment]
will include this in the next milestone

**Comment by Jason-Zhang9309** [comment]
A new release which contains nat gateway resources will be availiable by the end of this month

**Comment by Jason-Zhang9309** [comment]
resolved
