### ISSUE TITLE
The node_pool resource unavailable in the provider G42cloud provider and documentation

### ISSUE THREAD

**Issue by bshyrokov** [g42cloud-terraform/terraform-provider-g42cloud#19]
Could you please add the necessary resources for CCE?

### Terraform Version
```

provider registry.terraform.io/g42cloud-terraform/g42cloud v0.3.0
provider[registry.terraform.io/huaweicloud/huaweicloud] 1.23.1
```
### Expected Behavior
Create CPU and GPU node pool using terraform and official provider

### Actual Behavior
The resources are missing in the provider.

Could you please add the data source for receiving available addons and the addon version for the required cluster id

**Comment by niuzhenguo** [comment]
@bshyrokov You mean the addon templates or addons that already installed to the specified cluster?

**Comment by bshyrokov** [comment]
In my understanding, installed addons should be an attribute of the cluster.
It might be worth considering adding an optional attribute "Addons" to the resource g42cloud_cce_cluster and datasource.

In this request, I mean prepared templates for add to the cluster.
The main goal of this datasource is to receive the actual version of the addon.

**Comment by Jason-Zhang9309** [comment]
cce resources will be contained in the version which should be released by the end of this month

**Comment by Jason-Zhang9309** [comment]
resolved
