### ISSUE TITLE
The autoscaler add-on installation issue.

### ISSUE THREAD

**Issue by bshyrokov** [g42cloud-terraform/terraform-provider-g42cloud#20]
The issue with autoscaler add-on installation.

Terraform v0.13.4
    provider registry.terraform.io/g42cloud-terraform/g42cloud v0.3.0
    provider registry.terraform.io/hashicorp/random v3.1.0
    provider[registry.terraform.io/huaweicloud/huaweicloud] 1.23.1
    
### Affected Resource(s)
- huaweicloud_cce_addon

- g42cloud_cce_addon is missing in the provider

### Terraform Configuration Files
https://gist.github.com/bshyrokov/293c825efba37fdf4a57677abcd1d39b

### Debug Output
https://gist.github.com/bshyrokov/d2dc6326afb1bb83559fcf3093f87777

### Expected Behavior
Successful installation of the autoscaler add-on to the cluster

Actual Behavior
```
huaweicloud_cce_addon.addon_autoscaler: Still creating... [8m40s elapsed]

Error: Error creating HuaweiCloud CCEAddon: Post "https://22aaa9b7-a1ff-11eb-a272-0255ac100037.cce.ae-ad-1.vb.g42cloud.com:443/api/v3/addons": HuaweiCloud connection error, retries exhausted. Aborting. Last error was: dial tcp 91.201.4.126:443: connect: operation timed out

  on main.tf line 143, in resource "huaweicloud_cce_addon" "addon_autoscaler":
 143: resource "huaweicloud_cce_addon" "addon_autoscaler" {

```
Steps to Reproduce
1. `terraform init`
2. `terraform plan`
3. `terraform apply`

**Comment by Jason-Zhang9309** [comment]
It seems to be a network problem.

**Comment by Jason-Zhang9309** [comment]
resolved
