### ISSUE TITLE
Remove any reference to Sbercloud/Huawei cloud

### ISSUE THREAD

**Issue by Bulat-Gumerov** [g42cloud-terraform/terraform-provider-g42cloud#56]
For example:
https://github.com/g42cloud-terraform/terraform-provider-g42cloud/blob/575b12bf8441012cdd020f9d148d571ee27987ee/g42cloud/provider.go#L90
Region name is Moscow
https://github.com/g42cloud-terraform/terraform-provider-g42cloud/blob/bf6535d25f047fe1da0cffe56f0b7b24620869fc/g42cloud/resource_g42cloud_dms_instance_v1.go#L232
https://github.com/g42cloud-terraform/terraform-provider-g42cloud/blob/bf6535d25f047fe1da0cffe56f0b7b24620869fc/g42cloud/resource_g42cloud_dms_instance_v1.go#L172
Sbercloud
https://github.com/g42cloud-terraform/terraform-provider-g42cloud/search?q=.ru
Couple of reference links to the Sbercloud documentation

**Comment by Jason-Zhang9309** [comment]
@Bulat-Gumerov Thank you for pointing out these problems, we will fix them asap.
