### ISSUE TITLE
Add support to encrypt the ECS system disk with KMS

### ISSUE THREAD

**Issue by Bulat-Gumerov** [g42cloud-terraform/terraform-provider-g42cloud#66]
We can create a separate EVS volume for data disk like in this example:
https://github.com/g42cloud-terraform/terraform-provider-g42cloud/blob/main/docs/resources/evs_volume.md#example-usage-with-kms-encryption
But can we do the same for the system disk?
From this document it is unclear:
https://github.com/g42cloud-terraform/terraform-provider-g42cloud/blob/main/docs/resources/compute_instance.md

**Comment by Jason-Zhang9309** [comment]
fixed in #69
